module.exports = {
  purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      // These keyframes will be used when generating animation sequencing utilities
      keyframes: {
        "slide-up": {
          "0%": { transform: "translateY(24px)", opacity: 0 },
          "100%": { transform: "translateY(0)", opacity: 1 },
        },
        "fade-in": {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        drop: {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(1.05)" },
        },
      },
    },
    // Animation sequencing plugin options
    animationSequence: {
      // Utility will be generated using the [index + 1] of these delay values
      sequence: ["0s", ".25s", ".50s", ".75s", "1s"],
      options: {
        // Default animation duration for sequenced animations
        // can be overridden via animation-duration utilities generated by the plugin
        duration: "0.5s",
        // Default animation timing function for animations
        easing: "ease-in-out",
        // Default fill mode applied to animations
        fillMode: "both",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require("./plugins/animation-sequencing")],
};
